project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Classes/EAGER.qmd
    - Classes/UC_Berkeley.qmd
    - Classes/IntDataAnalysis.qmd
    - Classes/DataScience.qmd
    - Classes/CompStats.qmd
    - Projects/EAGER/Blog.qmd  
    - Projects/DataScience/SoCalRentProject.qmd
    - Projects/DataScience/FlowerProject.qmd
    - Projects/CompStats/ForniteMicroTransactions/Fornite_MicroTransactions.qmd
    - Projects/CompStats/Baseball/Baseball.qmd
    - Projects/CompStats/LongCOVID/LongCOVID.qmd
    - Projects/IntDataAnalysis/CarPrices/Cars4Sale.qmd
    - Projects/IntDataAnalysis/COVID/COVID.qmd
    - Projects/IntDataAnalysis/Earthquakes/Earthquake.qmd

website:
  title: "Natalie Torres"
  navbar:
    left:
      - href: Classes/EAGER.html
        text: EAGER
      - href: Classes/UC_Berkeley.html
        text: "UC Berkeley Research"
      - href: Classes/DataScience.html
        text: "Foundations of Data Science"
      - href: Classes/CompStats.html
        text: "Computational Statistics"
      - href: Classes/IntDataAnalysis.html
        text: "Intermediate Data Analysis"

format:
  html:
    theme: minty
    css: tabs.css
    toc: true
    code-fold: true
    code-summary: "Show code"
    highlight-style: dracula
