project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - EAGER.qmd
    - Projects/EAGER/blog.qmd  
    - UC_Berkeley.qmd
    - SoCalRentProject.qmd
    - FlowerProject.qmd
    - Projects/CompStats/Fornite_MicroTransactions.qmd
    - Projects/CompStats/Baseball.qmd
    - Projects/CompStats/LongCOVID.qmd
    - Projects/IntDataAnalysis/CarPrices/Cars4Sale.qmd
    - Projects/IntDataAnalysis/COVID/COVID.qmd
    - Projects/IntDataAnalysis/Earthquakes/Earthquake.qmd

website:
  title: "Natalie Torres Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: EAGER.qmd
        text: EAGER
      - href: UC_Berkeley.qmd
        text: "UC Berkeley"
      - href: SoCalRentProject.qmd
        text: "Data Science"
      - href: FlowerProject.qmd
        text: "Data Science"
      - href: Projects/CompStats/Fornite_MicroTransactions.qmd
        text: "Comp Stats"
      - href: Projects/IntDataAnalysis/CarPrices/Cars4Sale.qmd
        text: "Intermediate Data Analysis"

format:
  html:
    theme: minty
    toc: true
    code-fold: true
    code-summary: "Show code"
    highlight-style: dracula
